### ISSUE TITLE
Specify License

### ISSUE THREAD

**Issue by srinathh** [dmytrodanylyk/android-concurrent-database#1]
License is not specified - are u releasing this on an open-source license? It seems to be a pretty useful drop-in class vs. people having to write up their own

**Comment by dmytrodanylyk** [comment]
Yes this is open source. [License](https://github.com/dmytrodanylyk/android-concurrent-database/blob/master/LICENSE.md).

**Comment by srinathh** [comment]
Thanks!

Best Regards,
Srinath
_Blog:_ Curiosity & the Geek http://srinathh.github.io/
